isa:
  appid: 1111
  searchParams: kws_gen_one_best=true,kws_search_ls=true,kws_ls_duration=3000,search_it=true,search_it_dur=100
  xmlOption: true
  maxEngine: 2
  configs:
    #渠道编号(对应能力平台的地区编号)
    - resourceCode: xunfei
      #语音格式
      voiceFormat: audio/L16;rate=8000
      #引擎厂家
      manufacturer: iat
      #语言模型
      lang: sms
      #声学模型
      acous: xunfei
    - resourceCode: henan
      voiceFormat: audio/L8;rate=8000
      manufacturer: srv_rec
      #语言模型
      lang: sms
      #声学模型
      acous: henan
      #小包资源
      extraBundle:
      #热词
      hotWord:
    - resourceCode: hebei
      voiceFormat: audio/L8;rate=6000
      manufacturer: srv_rec
      #语言模型
      lang: sms
      #声学模型
      acous: hebei

#----------------------------常用音频格式参数-----------------------------------
#audio/basic
#audio/basic;stereo
#audio/x-alaw-basic
#audio/x-alaw-basic;stereo
#audio/L8;rate=8000
#audio/L8;rate=8000;stereo
#udio/L16;rate=8000
#audio/L16;rate=8000;stereo
#audio/voxware;rate=6000
#audio/voxware;rate=8000
#audio/g.726
#audio/g.729

