server:
  port: 9090
spring:
  kafka:
    bootstrap-servers:
    - 192.168.92.24:9092;192.168.92.24:9093;192.168.92.24:9094
    consumer:
      group-id: task
  redis:
    host: localhost
    port: 6379
  rocketmq:
    nameserver: 192.168.92.24:9876
    producer-group-name: group-result
