filters:
  filterList:
    - channelId: 1
      key: number
      type: number
      priority: 3
      value: 50
    - channelId: 1
      key: number
      type: number
      priority: 3
      from: 50
      to: 100
      intervalType: 3
